import { StyleSheet } from "react-native";
import Colors from "../../constants/colors";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors.background,
  },
  topBar: {
    paddingTop: 50,
    paddingHorizontal: 20,
    paddingBottom: 10,
    backgroundColor: Colors.background,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  reportChip: {
    backgroundColor: 'rgba(255,255,255,0.06)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.12)',
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 999,
  },
  reportChipDisabled: {
    opacity: 0.6,
  },
  reportChipText: {
    color: 'rgba(255,255,255,0.9)',
    fontWeight: '900',
    fontSize: 12,
  },
  backButtonTop: {
    alignSelf: 'flex-start',
    paddingVertical: 8,
    paddingHorizontal: 12,
  },
  backButtonText: {
    color: Colors.primary,
    fontSize: 16,
    fontWeight: '600',
  },
  loadingContainer: {
    flex: 1,
    backgroundColor: Colors.background,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 16,
  },
  loadingText: {
    color: 'rgba(255,255,255,0.7)',
    fontSize: 15,
  },
  backButton: {
    marginTop: 12,
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(255,23,68,0.4)',
  },
  scrollContent: {
    paddingBottom: 100,
  },
  imageContainer: {
    position: 'relative',
    height: 280,
  },
  image: {
    width: '100%',
    height: '100%',
    resizeMode: 'cover',
  },
  priceBadge: {
    position: 'absolute',
    top: 20,
    right: 20,
    backgroundColor: Colors.primary,
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 24,
  },
  priceText: {
    color: Colors.background,
    fontSize: 18,
    fontWeight: '900',
  },
  genreBadge: {
    position: 'absolute',
    bottom: 20,
    left: 20,
    backgroundColor: 'rgba(11,11,14,0.85)',
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 18,
  },
  genreText: {
    color: '#ffffff',
    fontSize: 14,
    fontWeight: '700',
    textTransform: 'uppercase',
  },
  content: {
    padding: 20,
    gap: 20,
  },
  title: {
    color: '#fff',
    fontSize: 28,
    fontWeight: '800',
  },
  description: {
    color: 'rgba(255,255,255,0.7)',
    fontSize: 16,
    lineHeight: 24,
  },
  errorText: {
    color: '#f97316',
    fontSize: 14,
    lineHeight: 20,
  },
  infoSection: {
    gap: 14,
  },
  infoRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  infoIcon: {
    fontSize: 18,
    marginRight: 12,
    width: 26,
  },
  infoText: {
    color: '#fff',
    fontSize: 16,
    flex: 1,
  },
  linkText: {
    color: Colors.primary,
    fontSize: 16,
    fontWeight: '600',
    textDecorationLine: 'underline',
  },
  djList: {
    flex: 1,
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'center',
    gap: 6,
  },
  djChip: {
    paddingVertical: 2,
  },
  calendarOutlineButton: {
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.35)',
    borderRadius: 14,
    paddingVertical: 12,
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 48,
    marginBottom: -6,
  },
  calendarOutlineButtonDisabled: {
    opacity: 0.58,
  },
  calendarOutlineButtonText: {
    color: '#fff',
    fontSize: 15,
    fontWeight: '800',
  },
  cgvRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginBottom: 14,
    marginTop: 4,
  },
  cgvCheckbox: {
    width: 22,
    height: 22,
    borderRadius: 6,
    borderWidth: 2,
    borderColor: 'rgba(255,23,68,0.6)',
    marginRight: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  cgvCheckboxChecked: {
    backgroundColor: Colors.primary,
    borderColor: Colors.primary,
  },
  cgvCheckmark: {
    color: Colors.background,
    fontSize: 14,
    fontWeight: '800',
  },
  cgvTextWrap: {
    flex: 1,
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'center',
  },
  cgvText: {
    color: 'rgba(255,255,255,0.85)',
    fontSize: 13,
  },
  cgvLink: {
    color: Colors.primary,
    fontSize: 13,
    fontWeight: '700',
  },
  buyButton: {
    backgroundColor: Colors.primary,
    paddingVertical: 18,
    borderRadius: 16,
    alignItems: 'center',
  },
  buyButtonDisabled: {
    opacity: 0.6,
  },
  buyButtonText: {
    color: Colors.background,
    fontSize: 18,
    fontWeight: '800',
  },
  pastEventSection: {
    gap: 16,
  },
  pastEventText: {
    color: 'rgba(255,255,255,0.6)',
    fontSize: 14,
    textAlign: 'center',
  },
  rateButton: {
    backgroundColor: 'rgba(255,23,68,0.2)',
    borderWidth: 1,
    borderColor: 'rgba(255,23,68,0.5)',
    paddingVertical: 18,
    borderRadius: 16,
    alignItems: 'center',
  },
  rateButtonText: {
    color: Colors.primary,
    fontSize: 18,
    fontWeight: '700',
  },
  dateEditor: {
    marginTop: 16,
    backgroundColor: '#1a1a1f',
    borderWidth: 1,
    borderColor: 'rgba(255,23,68,0.3)',
    borderRadius: 12,
    padding: 16,
  },
  dateEditorLabel: {
    color: Colors.primary,
    fontSize: 14,
    fontWeight: '600',
    marginBottom: 8,
  },
  dateEditorInput: {
    backgroundColor: Colors.background,
    borderWidth: 1,
    borderColor: 'rgba(255,23,68,0.3)',
    borderRadius: 8,
    padding: 12,
    color: '#fff',
    fontSize: 14,
    marginBottom: 12,
  },
  dateEditorButton: {
    backgroundColor: Colors.primary,
    borderRadius: 8,
    paddingVertical: 10,
    alignItems: 'center',
  },
  dateEditorButtonText: {
    color: Colors.background,
    fontSize: 14,
    fontWeight: '700',
  },
  warningCard: {
    backgroundColor: 'rgba(250,204,21,0.1)',
    borderWidth: 1,
    borderColor: 'rgba(250,204,21,0.4)',
    borderRadius: 16,
    padding: 16,
    marginTop: 16,
  },
  warningText: {
    color: '#facc15',
    fontSize: 14,
    lineHeight: 20,
    marginBottom: 12,
  },
  profileButton: {
    backgroundColor: Colors.primary,
    paddingVertical: 12,
    borderRadius: 12,
    alignItems: 'center',
  },
  profileButtonText: {
    color: Colors.background,
    fontSize: 16,
    fontWeight: '700',
  },
  friendsSection: {
    marginTop: 20,
    padding: 16,
    backgroundColor: 'rgba(255,23,68,0.08)',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: 'rgba(255,23,68,0.25)',
  },
  friendsSectionTitle: {
    color: Colors.primary,
    fontSize: 16,
    fontWeight: '800',
    marginBottom: 4,
  },
  friendsSectionHint: {
    color: 'rgba(255,255,255,0.6)',
    fontSize: 13,
    marginBottom: 12,
  },
  friendsButton: {
    backgroundColor: 'rgba(255,23,68,0.3)',
    borderWidth: 1,
    borderColor: Colors.primary,
    paddingVertical: 14,
    borderRadius: 14,
    alignItems: 'center',
    marginTop: 8,
  },
  friendsButtonDisabled: {
    opacity: 0.6,
  },
  friendsButtonText: {
    color: '#fff',
    fontSize: 15,
    fontWeight: '700',
  },
  groupCard: {
    backgroundColor: 'rgba(255,255,255,0.05)',
    borderRadius: 12,
    padding: 12,
    marginBottom: 8,
  },
  groupHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  groupName: {
    color: '#fff',
    fontSize: 15,
    fontWeight: '700',
  },
  inviteMoreBtn: {
    paddingVertical: 6,
    paddingHorizontal: 12,
    backgroundColor: 'rgba(255,23,68,0.3)',
    borderRadius: 8,
  },
  inviteMoreBtnText: {
    color: Colors.primary,
    fontSize: 13,
    fontWeight: '600',
  },
  groupMembers: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  memberChip: {
    backgroundColor: 'rgba(255,255,255,0.1)',
    paddingVertical: 6,
    paddingHorizontal: 10,
    borderRadius: 8,
  },
  memberChipText: {
    color: 'rgba(255,255,255,0.9)',
    fontSize: 13,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.6)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  modalContent: {
    width: '100%',
    maxWidth: 400,
    maxHeight: '80%',
    backgroundColor: '#141419',
    borderRadius: 18,
    padding: 20,
    borderWidth: 1,
    borderColor: 'rgba(255,23,68,0.3)',
  },
  modalTitle: {
    color: '#fff',
    fontSize: 18,
    fontWeight: '800',
    marginBottom: 4,
  },
  modalHint: {
    color: 'rgba(255,255,255,0.6)',
    fontSize: 13,
    marginBottom: 16,
  },
  friendsList: {
    maxHeight: 220,
    marginBottom: 16,
  },
  friendItem: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 12,
    paddingHorizontal: 14,
    backgroundColor: 'rgba(255,255,255,0.06)',
    borderRadius: 10,
    marginBottom: 8,
  },
  friendItemSelected: {
    backgroundColor: 'rgba(255,23,68,0.2)',
    borderWidth: 1,
    borderColor: 'rgba(255,23,68,0.5)',
  },
  friendItemText: {
    color: '#fff',
    fontSize: 15,
    fontWeight: '600',
  },
  friendItemCheck: {
    color: Colors.primary,
    fontSize: 16,
    fontWeight: '800',
  },
  modalActions: {
    flexDirection: 'row',
    gap: 12,
  },
  modalCancelBtn: {
    flex: 1,
    paddingVertical: 14,
    borderRadius: 12,
    backgroundColor: 'rgba(255,255,255,0.1)',
    alignItems: 'center',
  },
  modalCancelText: {
    color: 'rgba(255,255,255,0.9)',
    fontSize: 15,
    fontWeight: '700',
  },
  modalInviteBtn: {
    flex: 1,
    paddingVertical: 14,
    borderRadius: 12,
    backgroundColor: Colors.primary,
    alignItems: 'center',
  },
  modalInviteBtnDisabled: {
    opacity: 0.5,
  },
  modalInviteText: {
    color: Colors.background,
    fontSize: 15,
    fontWeight: '800',
  },
  tierSection: {
    marginBottom: 16,
  },
  tierSectionTitle: {
    color: 'rgba(255,255,255,0.9)',
    fontSize: 15,
    fontWeight: '700',
    marginBottom: 10,
  },
  tierChip: {
    paddingVertical: 12,
    paddingHorizontal: 14,
    marginBottom: 8,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.2)',
    backgroundColor: 'rgba(255,255,255,0.06)',
  },
  tierChipSelected: {
    borderColor: Colors.primary,
    backgroundColor: 'rgba(255,23,68,0.22)',
  },
  tierChipDisabled: {
    opacity: 0.45,
  },
  tierChipLabel: {
    color: '#fff',
    fontSize: 14,
    fontWeight: '600',
  },
  tierChipLabelSelected: {
    color: '#fff',
  },
  tierChipLabelDisabled: {
    color: 'rgba(255,255,255,0.55)',
  },
  helperTextTier: {
    color: '#fbbf24',
    fontSize: 13,
    lineHeight: 18,
    textAlign: 'center',
  },
});

