import { StyleSheet, Dimensions } from 'react-native';
import Colors from '../../constants/colors';

const { width } = Dimensions.get('window');

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors.background,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  loadingText: {
    color: '#fff',
    marginTop: 12,
  },
  errorContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  errorText: {
    color: 'rgba(255,255,255,0.6)',
    fontSize: 16,
  },
  header: {
    position: 'relative',
  },
  backgroundImage: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
  },
  backgroundImageContent: {
    width: '100%',
    height: '100%',
    opacity: 0.3,
  },
  profileSection: {
    justifyContent: 'flex-end',
    alignItems: 'center',
    paddingBottom: 20,
  },
  quickStatsRow: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 10,
    marginBottom: 10,
    paddingHorizontal: 20,
  },
  quickStatPill: {
    flex: 1,
    backgroundColor: 'rgba(11, 11, 14, 0.75)',
    borderWidth: 1,
    borderColor: 'rgba(77,163,255,0.25)',
    borderRadius: 14,
    paddingVertical: 10,
    paddingHorizontal: 12,
  },
  quickStatPillMuted: {
    borderColor: 'rgba(255,255,255,0.12)',
  },
  quickStatLabel: {
    color: 'rgba(255,255,255,0.65)',
    fontSize: 11,
    fontWeight: '800',
    textTransform: 'uppercase',
    marginBottom: 6,
  },
  quickStatValueRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
  },
  quickStatStars: {
    flexShrink: 1,
    alignItems: 'flex-end',
    justifyContent: 'center',
  },
  quickStatValue: {
    color: Colors.primary,
    fontSize: 18,
    fontWeight: '900',
  },
  quickStatValueSmall: {
    color: '#fff',
    fontSize: 13,
    fontWeight: '800',
  },
  headerBadgesRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
    gap: 10,
    paddingHorizontal: 20,
    marginTop: 4,
  },
  profileImageContainer: {
    width: 120,
    height: 120,
    borderRadius: 60,
    borderWidth: 3,
    borderColor: Colors.primary,
    overflow: 'hidden',
    marginBottom: 12,
  },
  profileImage: {
    width: '100%',
    height: '100%',
  },
  djName: {
    color: '#fff',
    fontSize: 28,
    fontWeight: '800',
    marginBottom: 4,
  },
  djLocation: {
    color: '#fff',
    fontSize: 16,
    marginBottom: 16,
  },
  bookButton: {
    backgroundColor: 'transparent',
    borderWidth: 2,
    borderColor: Colors.primary,
    borderRadius: 8,
    paddingVertical: 10,
    paddingHorizontal: 24,
  },
  bookButtonSelected: {
    backgroundColor: Colors.primary,
  },
  bookButtonText: {
    color: Colors.primary,
    fontSize: 14,
    fontWeight: '700',
    textTransform: 'uppercase',
  },
  bookButtonDisabled: {
    borderColor: 'rgba(255,255,255,0.3)',
    backgroundColor: 'rgba(255,255,255,0.1)',
  },
  bookButtonTextDisabled: {
    color: 'rgba(255,255,255,0.6)',
  },
  followButton: {
    marginTop: 12,
    backgroundColor: 'transparent',
    borderWidth: 2,
    borderColor: Colors.primary,
    borderRadius: 8,
    paddingVertical: 10,
    paddingHorizontal: 24,
  },
  followButtonActive: {
    backgroundColor: 'rgba(77,163,255,0.2)',
    borderColor: Colors.primary,
  },
  followButtonText: {
    color: Colors.primary,
    fontSize: 14,
    fontWeight: '700',
    textTransform: 'uppercase',
  },
  followButtonTextActive: {
    color: Colors.primary,
  },
  card: {
    marginHorizontal: 20,
    marginTop: 16,
    backgroundColor: '#1a1a1f',
    borderWidth: 1,
    borderColor: 'rgba(77,163,255,0.22)',
    borderRadius: 18,
    padding: 18,
  },
  sectionTitle: {
    color: Colors.primary,
    fontSize: 16,
    fontWeight: '700',
    marginBottom: 12,
    textTransform: 'uppercase',
  },
  streamSectionIntro: {
    color: 'rgba(255,255,255,0.55)',
    fontSize: 12,
    lineHeight: 17,
    marginTop: -6,
    marginBottom: 14,
  },
  infoItem: {
    marginBottom: 12,
  },
  unavailableHint: {
    marginTop: 8,
    color: 'rgba(255,255,255,0.6)',
    fontSize: 12,
    fontStyle: 'italic',
  },
  infoLabel: {
    color: 'rgba(255,255,255,0.6)',
    fontSize: 12,
    marginBottom: 4,
  },
  infoValue: {
    color: '#fff',
    fontSize: 14,
    fontWeight: '600',
  },
  bioText: {
    color: 'rgba(255,255,255,0.8)',
    fontSize: 14,
    lineHeight: 20,
  },
  bioTextEmpty: {
    color: 'rgba(255,255,255,0.55)',
    fontStyle: 'italic',
  },
  badgesRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    marginBottom: 12,
  },
  badge: {
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 999,
    backgroundColor: 'rgba(77,163,255,0.16)',
    borderWidth: 1,
    borderColor: 'rgba(77,163,255,0.28)',
  },
  badgeText: {
    color: '#fff',
    fontSize: 13,
    fontWeight: '800',
  },
  badgeSecondary: {
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 999,
    backgroundColor: 'rgba(255,255,255,0.06)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.12)',
  },
  badgeSecondaryText: {
    color: '#fff',
    fontSize: 13,
    fontWeight: '800',
  },
  badgesHint: {
    color: 'rgba(255,255,255,0.6)',
    fontSize: 13,
    fontStyle: 'italic',
    marginBottom: 12,
  },
  soundcloudButton: {
    borderWidth: 1,
    borderColor: 'rgba(77,163,255,0.45)',
    backgroundColor: 'rgba(77,163,255,0.10)',
    borderRadius: 14,
    paddingVertical: 12,
    paddingHorizontal: 14,
    alignItems: 'center',
  },
  soundcloudButtonText: {
    color: Colors.primary,
    fontSize: 14,
    fontWeight: '900',
  },
  streamBlock: {
    gap: 0,
  },
  streamProviderBlock: {},
  streamProviderBlockSpaced: {
    marginTop: 18,
    paddingTop: 16,
    borderTopWidth: 1,
    borderTopColor: 'rgba(255,255,255,0.1)',
  },
  streamProviderLabel: {
    color: 'rgba(255,255,255,0.75)',
    fontSize: 12,
    fontWeight: '800',
    marginBottom: 10,
    letterSpacing: 0.8,
  },
  streamPrimaryButton: {
    borderWidth: 1,
    borderColor: 'rgba(77,163,255,0.5)',
    backgroundColor: 'rgba(77,163,255,0.14)',
    borderRadius: 14,
    paddingVertical: 12,
    paddingHorizontal: 14,
    alignItems: 'center',
    marginBottom: 8,
  },
  streamPrimaryButtonText: {
    color: '#fff',
    fontSize: 15,
    fontWeight: '900',
  },
  streamSecondaryButton: {
    paddingVertical: 8,
    alignItems: 'center',
  },
  streamSecondaryButtonText: {
    color: Colors.primary,
    fontSize: 13,
    fontWeight: '700',
    textDecorationLine: 'underline',
  },
  emptyHint: {
    color: 'rgba(255,255,255,0.6)',
    fontSize: 13,
    fontStyle: 'italic',
  },
  audioPlayer: {
    flexDirection: 'row',
    paddingHorizontal: 20,
    marginBottom: 30,
    gap: 16,
  },
  audioInfo: {
    flex: 1,
  },
  audioTitle: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '700',
    marginBottom: 12,
  },
  audioControls: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  playButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: Colors.primary,
    justifyContent: 'center',
    alignItems: 'center',
  },
  playIcon: {
    color: Colors.background,
    fontSize: 16,
    marginLeft: 2,
  },
  playIconWhite: {
    color: '#fff',
    fontSize: 20,
    marginLeft: 3,
    fontWeight: 'bold',
  },
  progressBar: {
    flex: 1,
    height: 4,
    backgroundColor: 'rgba(255,255,255,0.2)',
    borderRadius: 2,
    overflow: 'hidden',
  },
  progressFill: {
    height: '100%',
    backgroundColor: Colors.primary,
  },
  duration: {
    color: 'rgba(255,255,255,0.6)',
    fontSize: 12,
  },
  photoThumbnails: {
    flexDirection: 'row',
    gap: 8,
  },
  thumbnail: {
    width: 60,
    height: 60,
    borderRadius: 8,
  },
  mediaContent: {
    paddingHorizontal: 20,
    marginBottom: 30,
  },
  videoRow: {
    gap: 12,
    paddingBottom: 6,
    paddingRight: 10,
  },
  videoCard: {
    width: 190,
    backgroundColor: 'rgba(255,255,255,0.05)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.10)',
    borderRadius: 16,
    padding: 10,
  },
  mediaSection: {
    paddingHorizontal: 20,
    paddingBottom: 20,
  },
  mediaButton: {
    backgroundColor: 'rgba(255,255,255,0.06)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.12)',
    borderRadius: 16,
    paddingVertical: 14,
    paddingHorizontal: 14,
    marginTop: 12,
  },
  mediaButtonActive: {
    borderColor: 'rgba(77,163,255,0.35)',
    backgroundColor: 'rgba(77,163,255,0.08)',
  },
  mediaButtonText: {
    color: '#fff',
    fontSize: 15,
    fontWeight: '900',
    marginBottom: 4,
  },
  mediaButtonSub: {
    color: 'rgba(255,255,255,0.65)',
    fontSize: 12,
    fontWeight: '600',
  },
  mediaSubtitle: {
    color: Colors.primary,
    fontSize: 13,
    fontWeight: '900',
    marginTop: 16,
    marginBottom: 10,
    textTransform: 'uppercase',
  },
  noMedia: {
    color: 'rgba(255,255,255,0.5)',
    fontSize: 14,
    textAlign: 'center',
    paddingVertical: 40,
    fontStyle: 'italic',
  },
  videoGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
  },
  videoItem: {
    width: (width - 60) / 2,
    marginBottom: 12,
  },
  videoThumbnail: {
    width: '100%',
    height: 120,
    borderRadius: 8,
    backgroundColor: '#1a1a1f',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 8,
    overflow: 'hidden',
    position: 'relative',
  },
  videoThumbnailImage: {
    width: '100%',
    height: '100%',
    position: 'absolute',
  },
  videoPlaceholder: {
    width: '100%',
    height: '100%',
    backgroundColor: 'rgba(255, 122, 26, 0.2)',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 12,
    position: 'absolute',
  },
  videoPlaceholderIcon: {
    fontSize: 32,
    marginBottom: 8,
  },
  videoPlaceholderText: {
    color: '#fff',
    fontSize: 11,
    fontWeight: '600',
    textAlign: 'center',
    opacity: 0.9,
  },
  playButtonOverlay: {
    position: 'absolute',
    width: 50,
    height: 50,
    borderRadius: 25,
    backgroundColor: 'rgba(255, 23, 68, 0.9)',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 1,
  },
  videoTitle: {
    color: '#fff',
    fontSize: 12,
    fontWeight: '600',
    marginTop: 4,
  },
  videoTitleUnavailable: {
    color: 'rgba(255,255,255,0.5)',
    textDecorationLine: 'line-through',
  },
  videoItemUnavailable: {
    opacity: 0.6,
  },
  unavailableOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.7)',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 8,
  },
  unavailableText: {
    color: '#fff',
    fontSize: 12,
    fontWeight: '700',
    textTransform: 'uppercase',
  },
  audioUnavailableContainer: {
    backgroundColor: 'rgba(255, 122, 26, 0.1)',
    borderWidth: 1,
    borderColor: 'rgba(255, 122, 26, 0.3)',
    borderRadius: 8,
    padding: 16,
    marginBottom: 16,
  },
  audioUnavailableTitle: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '700',
    marginBottom: 8,
  },
  audioUnavailableText: {
    color: 'rgba(255,255,255,0.7)',
    fontSize: 12,
    lineHeight: 18,
  },
  photoGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
  },
  photoItem: {
    width: (width - 60) / 3,
    height: (width - 60) / 3,
    borderRadius: 8,
    backgroundColor: '#1a1a1f',
  },
  photoModalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.92)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  photoModalImage: {
    width: '100%',
    height: '80%',
    borderRadius: 18,
  },
  photoModalClose: {
    position: 'absolute',
    top: 50,
    right: 20,
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: 'rgba(255,255,255,0.12)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.18)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  photoModalCloseText: {
    color: '#fff',
    fontSize: 18,
    fontWeight: '900',
  },
  bottomSection: {
    flexDirection: 'row',
    paddingHorizontal: 20,
    marginBottom: 30,
  },
  reviewsColumn: {
    flex: 1,
    paddingRight: 10,
  },
  equipmentColumn: {
    flex: 1,
    paddingLeft: 10,
  },
  reviewItem: {
    marginBottom: 16,
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(77,163,255,0.2)',
  },
  reviewHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
  },
  reviewIcon: {
    fontSize: 16,
    marginRight: 8,
  },
  reviewerName: {
    color: Colors.primary,
    fontSize: 14,
    fontWeight: '600',
  },
  reviewComment: {
    color: 'rgba(255,255,255,0.8)',
    fontSize: 13,
    marginTop: 6,
    lineHeight: 18,
  },
  noReviews: {
    color: 'rgba(255,255,255,0.5)',
    fontSize: 14,
    fontStyle: 'italic',
  },
  equipmentList: {
    gap: 8,
  },
  equipmentItem: {
    color: 'rgba(255,255,255,0.8)',
    fontSize: 14,
  },
  equipmentText: {
    color: 'rgba(255,255,255,0.8)',
    fontSize: 14,
    lineHeight: 20,
  },
  calendarSection: {
    paddingHorizontal: 20,
    marginBottom: 30,
  },
  calendarHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  calendarTitle: {
    color: '#fff',
    fontSize: 18,
    fontWeight: '700',
  },
  calendarArrow: {
    color: Colors.primary,
    fontSize: 20,
    fontWeight: '700',
  },
  eventBox: {
    backgroundColor: 'rgba(77,163,255,0.1)',
    borderWidth: 1,
    borderColor: 'rgba(77,163,255,0.3)',
    borderRadius: 12,
    padding: 16,
    marginBottom: 20,
  },
  eventDate: {
    color: Colors.primary,
    fontSize: 14,
    fontWeight: '700',
    marginBottom: 4,
  },
  eventName: {
    color: '#fff',
    fontSize: 18,
    fontWeight: '700',
  },
  eventVenue: {
    color: 'rgba(255,255,255,0.7)',
    fontSize: 14,
    marginTop: 4,
  },
  pastEventsTitle: {
    color: 'rgba(255,255,255,0.6)',
    fontSize: 12,
    fontWeight: '700',
    textTransform: 'uppercase',
    marginBottom: 12,
  },
  pastEventBox: {
    backgroundColor: 'rgba(255,255,255,0.05)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.1)',
    borderRadius: 8,
    padding: 12,
    marginBottom: 12,
  },
  pastEventDate: {
    color: 'rgba(255,255,255,0.6)',
    fontSize: 14,
  },
  pastEventName: {
    color: 'rgba(255,255,255,0.8)',
    fontSize: 14,
    marginTop: 4,
    fontWeight: '600',
  },
  backButton: {
    position: 'absolute',
    top: 50,
    left: 20,
    zIndex: 1000,
    paddingVertical: 8,
    paddingHorizontal: 12,
    backgroundColor: 'rgba(11, 11, 14, 0.7)',
    borderRadius: 8,
  },
  menuButton: {
    position: 'absolute',
    top: 50,
    right: 20,
    zIndex: 1000,
    paddingVertical: 8,
    paddingHorizontal: 10,
    backgroundColor: 'rgba(11, 11, 14, 0.7)',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(77,163,255,0.35)',
    minHeight: 44,
    minWidth: 44,
    alignItems: 'center',
    justifyContent: 'center',
  },
  backButtonText: {
    color: Colors.primary,
    fontSize: 16,
    fontWeight: '600',
  },
});
