import { StyleSheet } from 'react-native';
import Colors from '../../constants/colors';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors.background,
  },
  topBar: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingBottom: 10,
    backgroundColor: Colors.background,
  },
  backButtonTop: {
    paddingVertical: 8,
    paddingHorizontal: 12,
  },
  backButtonTopText: {
    color: Colors.primary,
    fontSize: 16,
    fontWeight: '600',
  },
  switchProfileButton: {
    paddingVertical: 8,
    paddingHorizontal: 12,
    backgroundColor: 'rgba(255, 122, 26, 0.2)',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: Colors.primary,
  },
  switchProfileButtonText: {
    color: Colors.primary,
    fontSize: 14,
    fontWeight: '600',
  },
  scroll: {
    flex: 1,
  },
  content: {
    padding: 20,
    paddingBottom: 40,
  },
  header: {
    alignItems: 'center',
    marginBottom: 24,
  },
  avatar: {
    width: 110,
    height: 110,
    borderRadius: 55,
    backgroundColor: Colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 16,
    overflow: 'hidden',
  },
  avatarImage: {
    width: 110,
    height: 110,
    borderRadius: 55,
  },
  avatarText: {
    color: Colors.background,
    fontSize: 54,
    fontWeight: '900',
  },
  title: {
    color: '#ffffff',
    fontSize: 24,
    fontWeight: '800',
  },
  subtitle: {
    color: 'rgba(255,255,255,0.6)',
    fontSize: 14,
    textAlign: 'center',
    marginTop: 6,
  },
  alertCard: {
    backgroundColor: '#141419',
    borderWidth: 1,
    borderColor: 'rgba(250,204,21,0.4)',
    borderRadius: 18,
    padding: 20,
    marginBottom: 20,
    gap: 12,
  },
  alertTitle: {
    color: '#facc15',
    fontSize: 18,
    fontWeight: '700',
  },
  alertText: {
    color: 'rgba(255,255,255,0.75)',
    fontSize: 14,
    lineHeight: 20,
  },
  alertButton: {
    backgroundColor: '#facc15',
    borderRadius: 12,
    paddingVertical: 12,
    alignItems: 'center',
  },
  alertButtonText: {
    color: Colors.background,
    fontSize: 15,
    fontWeight: '700',
  },
  card: {
    backgroundColor: '#1a1a1f',
    borderWidth: 1,
    borderColor: 'rgba(255,23,68,0.3)',
    borderRadius: 18,
    padding: 20,
    marginBottom: 20,
  },
  cardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  cardTitle: {
    color: '#ffffff',
    fontSize: 18,
    fontWeight: '700',
  },
  addProfileButton: {
    backgroundColor: 'rgba(255,23,68,0.25)',
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: 'rgba(255,23,68,0.5)',
  },
  addProfileButtonText: {
    color: Colors.primary,
    fontSize: 14,
    fontWeight: '700',
  },
  editButton: {
    color: Colors.primary,
    fontSize: 14,
    fontWeight: '600',
  },
  info: {
    gap: 12,
  },
  infoRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255,23,68,0.15)',
  },
  infoLabel: {
    color: 'rgba(255,255,255,0.7)',
    fontSize: 14,
  },
  infoValue: {
    color: '#ffffff',
    fontSize: 14,
    fontWeight: '600',
  },
  infoValueHighlight: {
    color: Colors.primary,
  },
  success: {
    color: '#10b981',
  },
  warning: {
    color: '#ef4444',
  },
  label: {
    color: 'rgba(255,255,255,0.7)',
    fontSize: 14,
    marginBottom: 8,
  },
  input: {
    backgroundColor: Colors.background,
    borderWidth: 1,
    borderColor: Colors.primary,
    borderRadius: 12,
    color: '#ffffff',
    fontSize: 16,
    padding: 12,
    marginBottom: 16,
  },
  emailVerifyBox: {
    marginTop: 10,
    padding: 12,
    borderRadius: 12,
    backgroundColor: 'rgba(255,255,255,0.06)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.10)',
    gap: 10,
  },
  codeInput: {
    marginBottom: 0,
  },
  smallButton: {
    paddingVertical: 10,
    borderRadius: 12,
    backgroundColor: 'rgba(255,255,255,0.10)',
    alignItems: 'center',
  },
  smallPrimaryButton: {
    paddingVertical: 10,
    borderRadius: 12,
    backgroundColor: '#fff',
    alignItems: 'center',
  },
  smallButtonDisabled: {
    opacity: 0.6,
  },
  smallButtonText: {
    color: '#fff',
    fontWeight: '700',
  },
  smallPrimaryButtonText: {
    color: Colors.background,
    fontWeight: '800',
  },
  editActions: {
    flexDirection: 'row',
    textAlign: 'center',
    gap: 10,
  },
  cancelButton: {
    flex: 1,
    borderWidth: 1,
    borderColor: 'rgba(255,23,68,0.3)',
    borderRadius: 12,
    paddingVertical: 14,
    alignItems: 'center',
    backgroundColor: '#1a1a1f',
  },
  cancelText: {
    color: '#ffffff',
    fontSize: 15,
    fontWeight: '600',
  },
  saveButton: {
    flex: 1,
    borderRadius: 12,
    paddingVertical: 14,
    alignItems: 'center',
    backgroundColor: Colors.primary,
  },
  saveText: {
    color: Colors.background,
    fontSize: 15,
    fontWeight: '700',
  },
  statsCard: {
    backgroundColor: '#1a1a1f',
    borderWidth: 1,
    borderColor: 'rgba(255,23,68,0.3)',
    borderRadius: 18,
    padding: 20,
    marginBottom: 20,
  },
  statsTitle: {
    color: '#ffffff',
    fontSize: 18,
    fontWeight: '700',
    marginBottom: 16,
  },
  statsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  statItem: {
    flex: 1,
    alignItems: 'center',
    paddingVertical: 12,
    borderRadius: 12,
    backgroundColor: Colors.background,
    marginHorizontal: 6,
  },
  statValue: {
    color: Colors.primary,
    fontSize: 28,
    fontWeight: '800',
    marginBottom: 6,
  },
  statLabel: {
    color: 'rgba(255,255,255,0.65)',
    fontSize: 12,
    textTransform: 'uppercase',
    letterSpacing: 1,
  },
  note: {
    backgroundColor: '#141419',
    borderWidth: 1,
    borderColor: 'rgba(255,23,68,0.2)',
    borderRadius: 16,
    padding: 18,
  },
  noteTitle: {
    color: Colors.primary,
    fontSize: 16,
    fontWeight: '700',
    marginBottom: 8,
  },
  noteText: {
    color: 'rgba(255,255,255,0.7)',
    fontSize: 14,
    lineHeight: 20,
  },
  profileActiveLabel: {
    color: Colors.primary,
    fontSize: 14,
    fontWeight: '600',
    marginBottom: 16,
  },
  profileSection: {
    marginBottom: 20,
  },
  profileSectionLast: {
    marginBottom: 4,
    paddingBottom: 4,
  },
  profileSectionTitle: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: '700',
    marginBottom: 12,
  },
  profileItem: {
    backgroundColor: '#141419',
    borderWidth: 1,
    borderColor: 'rgba(255,23,68,0.3)',
    borderRadius: 12,
    padding: 14,
    marginBottom: 8,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  profileItemActive: {
    borderColor: Colors.primary,
    backgroundColor: 'rgba(255,23,68,0.1)',
  },
  profileItemText: {
    color: '#ffffff',
    fontSize: 15,
    fontWeight: '500',
  },
  profileItemActiveBadge: {
    color: Colors.primary,
    fontSize: 12,
    fontWeight: '600',
  },
  profileItemRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
    gap: 8,
  },
  profileItemFlex: {
    flex: 1,
  },
  profileEditButton: {
    backgroundColor: 'rgba(255,23,68,0.3)',
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 10,
  },
  profileEditButtonText: {
    color: Colors.primary,
    fontSize: 13,
    fontWeight: '600',
  },
  noProfilesText: {
    color: 'rgba(255,255,255,0.5)',
    fontSize: 14,
    textAlign: 'center',
    marginVertical: 20,
  },
  noProfilesBox: {
    backgroundColor: '#141419',
    borderWidth: 1,
    borderColor: 'rgba(255,23,68,0.2)',
    borderRadius: 16,
    padding: 24,
    alignItems: 'center',
    marginTop: 12,
  },
  createProfileBtn: {
    backgroundColor: Colors.primary,
    paddingHorizontal: 24,
    paddingVertical: 14,
    borderRadius: 12,
    marginTop: 12,
  },
  createProfileBtnText: {
    color: Colors.background,
    fontSize: 15,
    fontWeight: '700',
  },
  rgpdDescription: {
    color: 'rgba(255,255,255,0.7)',
    fontSize: 13,
    marginBottom: 14,
    lineHeight: 18,
  },
  rgpdButtons: {
    gap: 10,
  },
  rgpdButton: {
    backgroundColor: 'rgba(255,255,255,0.12)',
    borderWidth: 1,
    borderColor: 'rgba(255,23,68,0.4)',
    borderRadius: 12,
    paddingVertical: 12,
    alignItems: 'center',
  },
  rgpdButtonDisabled: {
    opacity: 0.6,
  },
  rgpdButtonText: {
    color: '#fff',
    fontSize: 14,
    fontWeight: '600',
  },
  rgpdButtonDanger: {
    backgroundColor: 'rgba(239,68,68,0.2)',
    borderWidth: 1,
    borderColor: 'rgba(239,68,68,0.5)',
    borderRadius: 12,
    paddingVertical: 12,
    alignItems: 'center',
  },
  rgpdButtonDangerText: {
    color: '#ef4444',
    fontSize: 14,
    fontWeight: '600',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.6)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  modalCard: {
    backgroundColor: '#1a1a1f',
    borderRadius: 18,
    padding: 24,
    width: '100%',
    maxWidth: 400,
    borderWidth: 1,
    borderColor: 'rgba(255,23,68,0.3)',
  },
  modalTitle: {
    color: '#fff',
    fontSize: 18,
    fontWeight: '700',
    marginBottom: 12,
  },
  modalText: {
    color: 'rgba(255,255,255,0.8)',
    fontSize: 14,
    lineHeight: 20,
    marginBottom: 16,
  },
  modalInput: {
    backgroundColor: Colors.background,
    borderWidth: 1,
    borderColor: 'rgba(255,23,68,0.4)',
    borderRadius: 12,
    padding: 14,
    color: '#fff',
    marginBottom: 20,
  },
  modalActions: {
    flexDirection: 'row',
    gap: 12,
    justifyContent: 'flex-end',
  },
  modalCancelButton: {
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 12,
    backgroundColor: 'rgba(255,255,255,0.1)',
  },
  modalCancelText: {
    color: 'rgba(255,255,255,0.9)',
    fontSize: 14,
    fontWeight: '600',
  },
  modalDeleteButton: {
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 12,
    backgroundColor: '#ef4444',
  },
  modalButtonDisabled: {
    opacity: 0.5,
  },
  modalDeleteText: {
    color: '#fff',
    fontSize: 14,
    fontWeight: '700',
  },
});
