import { StyleSheet } from 'react-native';
import Colors, { primaryAlpha } from '../../constants/colors';
import { Layout, Radius, Spacing } from '../../constants/theme';

export const publicProfileStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors.background,
  },
  scrollContent: {
    paddingBottom: 140,
  },
  heroWrap: {
    marginBottom: Spacing.md,
  },
  banner: {
    height: 168,
    width: '100%',
    backgroundColor: Colors.backgroundElevated,
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  bannerImage: {
    ...StyleSheet.absoluteFillObject,
    width: '100%',
    height: '100%',
  },
  bannerOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(0,0,0,0.35)',
  },
  topOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: Spacing.md,
    zIndex: 2,
  },
  topBtn: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(0,0,0,0.4)',
  },
  identityRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    paddingHorizontal: Layout.screenPaddingHorizontal,
    marginTop: -36,
    gap: Spacing.md,
  },
  avatarWrap: {
    position: 'relative',
  },
  avatar: {
    width: 84,
    height: 84,
    borderRadius: 42,
    borderWidth: 3,
    borderColor: Colors.background,
    backgroundColor: Colors.backgroundElevated,
  },
  avatarPlaceholder: {
    width: 84,
    height: 84,
    borderRadius: 42,
    borderWidth: 3,
    borderColor: Colors.background,
    backgroundColor: primaryAlpha(0.2),
    alignItems: 'center',
    justifyContent: 'center',
  },
  verifiedBadge: {
    position: 'absolute',
    right: 0,
    bottom: 2,
    backgroundColor: Colors.background,
    borderRadius: 10,
  },
  identityMain: {
    flex: 1,
    paddingTop: 40,
    minWidth: 0,
  },
  nameRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.sm,
    flexWrap: 'wrap',
  },
  name: {
    fontSize: 22,
    lineHeight: 28,
    flexShrink: 1,
  },
  actionsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.sm,
    marginTop: Spacing.sm,
  },
  followBtn: {
    minWidth: 96,
    height: 36,
    paddingHorizontal: Spacing.md,
    borderRadius: Radius.pill,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: Colors.primary,
  },
  followBtnSecondary: {
    backgroundColor: Colors.backgroundElevated,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: Colors.borderSubtle,
  },
  followBtnText: {
    color: Colors.text,
    fontWeight: '700',
    fontSize: 13,
  },
  iconAction: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: Colors.backgroundElevated,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: Colors.borderSubtle,
  },
  metaLine: {
    marginTop: Spacing.sm,
    fontSize: 13,
    paddingHorizontal: Layout.screenPaddingHorizontal,
  },
  locRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    marginTop: 4,
    paddingHorizontal: Layout.screenPaddingHorizontal,
  },
  locText: {
    fontSize: 12,
    flex: 1,
  },
  bioBlock: {
    paddingHorizontal: Layout.screenPaddingHorizontal,
    marginTop: Spacing.md,
  },
  bioText: {
    lineHeight: 20,
    fontSize: 13,
  },
  seeMore: {
    color: Colors.primary,
    marginTop: 4,
    fontSize: 13,
    fontWeight: '600',
  },
  statsRow: {
    flexDirection: 'row',
    alignItems: 'stretch',
    marginTop: Spacing.lg,
    marginHorizontal: Layout.screenPaddingHorizontal,
    paddingVertical: Spacing.md,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderColor: 'rgba(255,255,255,0.1)',
  },
  statItem: {
    flex: 1,
    alignItems: 'center',
    gap: 2,
  },
  statDivider: {
    width: StyleSheet.hairlineWidth,
    backgroundColor: 'rgba(255,255,255,0.12)',
  },
  statValue: {
    color: Colors.text,
    fontSize: 16,
    fontWeight: '800',
  },
  statLabel: {
    fontSize: 11,
    textAlign: 'center',
  },
  extraActions: {
    paddingHorizontal: Layout.screenPaddingHorizontal,
    marginTop: Spacing.md,
    gap: Spacing.sm,
  },
  tabsWrap: {
    marginTop: Spacing.lg,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: 'rgba(255,255,255,0.1)',
  },
  tabsScroll: {
    paddingHorizontal: Layout.screenPaddingHorizontal,
    gap: Spacing.lg,
  },
  tabItem: {
    paddingVertical: Spacing.md,
    borderBottomWidth: 2,
    borderBottomColor: 'transparent',
  },
  tabItemActive: {
    borderBottomColor: Colors.primary,
  },
  tabLabel: {
    fontSize: 14,
    fontWeight: '600',
    color: Colors.textSecondary,
  },
  tabLabelActive: {
    color: Colors.text,
  },
  tabBody: {
    paddingTop: Spacing.lg,
    paddingHorizontal: Layout.screenPaddingHorizontal,
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: Spacing.md,
    marginTop: Spacing.md,
  },
  sectionTitle: {
    fontSize: 16,
  },
  seeAll: {
    color: Colors.primary,
    fontSize: 13,
    fontWeight: '600',
  },
  emptyHint: {
    textAlign: 'center',
    paddingVertical: Spacing.xl,
    lineHeight: 20,
  },
  aboutGrid: {
    flexDirection: 'row',
    gap: Spacing.md,
    marginTop: Spacing.md,
  },
  aboutDetails: {
    flex: 1,
    gap: Spacing.md,
  },
  aboutRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: Spacing.sm,
  },
  aboutRowText: {
    flex: 1,
    fontSize: 13,
    lineHeight: 18,
  },
  quoteCard: {
    flex: 1,
    backgroundColor: Colors.backgroundElevated,
    borderRadius: Radius.card,
    borderWidth: 0.5,
    borderColor: Colors.borderCard,
    padding: Spacing.lg,
    minHeight: 140,
  },
  quoteMark: {
    fontSize: 36,
    color: Colors.textMuted,
    lineHeight: 36,
    marginBottom: Spacing.sm,
  },
  quoteText: {
    fontSize: 13,
    lineHeight: 18,
    fontStyle: 'italic',
  },
  quoteAttr: {
    marginTop: Spacing.md,
    fontSize: 12,
  },
  socialRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: Spacing.sm,
    marginTop: 4,
  },
  socialChip: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: Colors.backgroundElevated,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: Colors.borderSubtle,
  },
  contactBtn: {
    marginTop: Spacing.sm,
    alignSelf: 'flex-start',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: Colors.primary,
    paddingHorizontal: Spacing.md,
    paddingVertical: Spacing.sm,
    borderRadius: Radius.pill,
  },
  contactBtnText: {
    color: Colors.text,
    fontWeight: '700',
    fontSize: 12,
  },
  eventsScroll: {
    gap: Spacing.md,
    paddingRight: Spacing.md,
    paddingBottom: Spacing.sm,
  },
  eventCard: {
    width: 240,
    height: 148,
    borderRadius: Radius.card,
    overflow: 'hidden',
    backgroundColor: Colors.backgroundElevated,
    borderWidth: 0.5,
    borderColor: Colors.borderCard,
  },
  eventImage: {
    ...StyleSheet.absoluteFillObject,
    width: '100%',
    height: '100%',
  },
  eventImageFallback: {
    ...StyleSheet.absoluteFillObject,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: Colors.backgroundElevated,
  },
  eventOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(0,0,0,0.48)',
  },
  eventBadge: {
    position: 'absolute',
    top: Spacing.sm,
    left: Spacing.sm,
    backgroundColor: 'rgba(0,0,0,0.55)',
    paddingHorizontal: Spacing.sm,
    paddingVertical: 3,
    borderRadius: Radius.sm,
  },
  eventBadgeText: {
    color: Colors.text,
    fontSize: 10,
    fontWeight: '800',
  },
  eventBottom: {
    position: 'absolute',
    left: Spacing.sm,
    right: Spacing.sm,
    bottom: Spacing.sm,
    flexDirection: 'row',
    alignItems: 'flex-end',
    gap: Spacing.sm,
  },
  eventTitle: {
    color: Colors.text,
    fontSize: 13,
    fontWeight: '700',
  },
  eventLoc: {
    fontSize: 11,
    marginTop: 2,
  },
  eventTags: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 4,
    marginTop: 4,
  },
  eventTag: {
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: Radius.pill,
    backgroundColor: 'rgba(255,255,255,0.12)',
  },
  eventTagText: {
    fontSize: 10,
    color: Colors.text,
  },
  eventArrow: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: 'rgba(255,255,255,0.12)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  mediaGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: Spacing.sm,
  },
  mediaThumb: {
    width: '48%',
    aspectRatio: 1,
    borderRadius: Radius.md,
    overflow: 'hidden',
    backgroundColor: Colors.backgroundElevated,
  },
  mediaThumbImage: {
    width: '100%',
    height: '100%',
  },
  mediaPlay: {
    ...StyleSheet.absoluteFillObject,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(0,0,0,0.25)',
  },
  reviewCard: {
    width: 220,
    backgroundColor: Colors.backgroundElevated,
    borderRadius: Radius.card,
    borderWidth: 0.5,
    borderColor: Colors.borderCard,
    padding: Spacing.md,
    marginRight: Spacing.md,
    gap: Spacing.sm,
  },
  reviewHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.sm,
  },
  reviewAvatar: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: primaryAlpha(0.2),
    alignItems: 'center',
    justifyContent: 'center',
  },
  reviewComment: {
    fontSize: 12,
    lineHeight: 17,
    fontStyle: 'italic',
  },
  highlightRow: {
    flexDirection: 'row',
    gap: Spacing.md,
    marginBottom: Spacing.sm,
  },
  highlightCard: {
    flex: 1,
    backgroundColor: Colors.backgroundElevated,
    borderRadius: Radius.card,
    borderWidth: 0.5,
    borderColor: Colors.borderCard,
    padding: Spacing.md,
    minHeight: 96,
    justifyContent: 'space-between',
  },
  highlightLabel: {
    fontSize: 11,
    marginBottom: Spacing.xs,
  },
  highlightTitle: {
    fontSize: 13,
    fontWeight: '700',
  },
});
