import { StyleSheet } from 'react-native';
import Colors from '../../constants/colors';
import { Layout, Radius, Spacing } from '../../constants/theme';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors.background,
  },
  centered: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  hubScroll: {
    flex: 1,
  },
  hubScrollContent: {
    paddingHorizontal: Layout.screenPaddingHorizontal,
  },
  hubTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: Spacing.xl,
    gap: Spacing.md,
  },
  hubTopAvatarWrap: {
    width: 44,
    height: 44,
    borderRadius: 22,
    overflow: 'hidden',
  },
  hubTopAvatar: {
    width: 44,
    height: 44,
    borderRadius: 22,
    borderWidth: 1.5,
    borderColor: Colors.primary,
  },
  hubTopAvatarFallback: {
    backgroundColor: Colors.backgroundElevated,
    alignItems: 'center',
    justifyContent: 'center',
  },
  hubTopText: {
    flex: 1,
  },
  hubGreeting: {
    fontSize: 22,
    lineHeight: 28,
  },
  hubSubtitle: {
    fontSize: 13,
    lineHeight: 18,
    color: Colors.textSecondary,
    marginTop: 2,
  },
  hubNotifBtn: {
    width: 44,
    height: 44,
    alignItems: 'center',
    justifyContent: 'center',
  },
  hubNotifBadge: {
    position: 'absolute',
    top: 4,
    right: 4,
  },
  hubProfileCard: {
    height: 220,
    borderRadius: Radius.card,
    overflow: 'hidden',
    marginBottom: Spacing.lg,
    backgroundColor: Colors.backgroundElevated,
    borderWidth: 0.5,
    borderColor: Colors.borderCard,
  },
  hubProfileBanner: {
    ...StyleSheet.absoluteFillObject,
    width: '100%',
    height: '100%',
  },
  hubProfileBannerFallback: {
    backgroundColor: Colors.backgroundElevated,
    alignItems: 'center',
    justifyContent: 'center',
  },
  hubProfileOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(0,0,0,0.5)',
  },
  hubVenueBadge: {
    position: 'absolute',
    top: Spacing.md,
    left: Spacing.md,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: 'rgba(0,0,0,0.45)',
    paddingHorizontal: Spacing.sm,
    paddingVertical: 4,
    borderRadius: Radius.pill,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: 'rgba(255,255,255,0.2)',
  },
  hubVenueBadgeText: {
    color: Colors.text,
    fontSize: 11,
    fontWeight: '600',
  },
  hubProfileViewBtn: {
    position: 'absolute',
    top: Spacing.md,
    right: Spacing.md,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: 'rgba(0,0,0,0.45)',
    paddingHorizontal: Spacing.md,
    paddingVertical: 6,
    borderRadius: Radius.pill,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: 'rgba(255,255,255,0.25)',
  },
  hubProfileViewBtnText: {
    color: Colors.text,
    fontSize: 12,
    fontWeight: '600',
  },
  hubProfileInfo: {
    position: 'absolute',
    left: Spacing.lg,
    right: Spacing.lg,
    bottom: Spacing.lg,
  },
  hubProfileNameRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.sm,
  },
  hubProfileName: {
    fontSize: 22,
    lineHeight: 28,
  },
  hubProfileMeta: {
    marginTop: 2,
    fontSize: 13,
  },
  hubProfileLocRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    marginTop: 4,
  },
  hubProfileLoc: {
    fontSize: 12,
    flex: 1,
  },
  hubProfileStats: {
    flexDirection: 'row',
    marginTop: Spacing.md,
    gap: Spacing.lg,
  },
  hubProfileStat: {
    gap: 2,
  },
  hubProfileStatValue: {
    color: Colors.text,
    fontSize: 16,
    fontWeight: '800',
  },
  hubProfileStatLabel: {
    fontSize: 11,
  },
  hubPendingBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: Colors.primary,
    borderRadius: Radius.button,
    paddingVertical: Spacing.md,
    paddingHorizontal: Spacing.lg,
    marginBottom: Spacing.lg,
  },
  hubPendingLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.sm,
    flex: 1,
  },
  hubPendingLabel: {
    color: Colors.text,
    fontWeight: '700',
    fontSize: 14,
  },
  hubPendingLink: {
    color: 'rgba(254,254,253,0.85)',
    fontWeight: '600',
    fontSize: 13,
  },
  hubSectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: Spacing.md,
    marginBottom: Spacing.md,
  },
  hubSectionTitleInline: {
    fontSize: 16,
  },
  hubSeeAll: {
    color: Colors.primary,
    fontSize: 13,
    fontWeight: '600',
  },
  hubStatsPeriod: {
    fontSize: 12,
  },
  hubGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  hubToolCard: {
    backgroundColor: Colors.backgroundElevated,
    borderRadius: Radius.card,
    borderWidth: 0.5,
    borderColor: Colors.borderCard,
    marginBottom: Spacing.md,
    padding: Spacing.lg,
    minHeight: 108,
    justifyContent: 'space-between',
    shadowColor: Colors.cardShadow,
    shadowOffset: { width: 2, height: 5 },
    shadowRadius: 8,
    shadowOpacity: 0.35,
    elevation: 3,
  },
  hubToolRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: Spacing.sm,
  },
  hubTileIconWrap: {
    width: 40,
    height: 40,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
  },
  hubTileBadge: {
    position: 'absolute',
    top: -4,
    right: -4,
  },
  hubTileLabel: {
    fontSize: 14,
    fontWeight: '700',
    color: Colors.text,
  },
  hubTileHint: {
    fontSize: 11,
    color: Colors.textMuted,
    marginTop: 2,
  },
  hubEmptyEvents: {
    backgroundColor: Colors.backgroundElevated,
    borderRadius: Radius.card,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: Colors.borderSubtle,
    padding: Spacing.xl,
    marginBottom: Spacing.sm,
  },
  hubEmptyEventsText: {
    textAlign: 'center',
    lineHeight: 20,
  },
  hubEventsScroll: {
    gap: Spacing.md,
    paddingRight: Spacing.md,
    paddingBottom: Spacing.sm,
  },
  hubEventCard: {
    height: 168,
    borderRadius: Radius.card,
    overflow: 'hidden',
    backgroundColor: Colors.backgroundElevated,
    borderWidth: 0.5,
    borderColor: Colors.borderCard,
  },
  hubEventImage: {
    ...StyleSheet.absoluteFillObject,
    width: '100%',
    height: '100%',
  },
  hubEventImageFallback: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: Colors.backgroundElevated,
    alignItems: 'center',
    justifyContent: 'center',
  },
  hubEventOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(0,0,0,0.5)',
  },
  hubEventBadge: {
    position: 'absolute',
    top: Spacing.md,
    left: Spacing.md,
    backgroundColor: 'rgba(0,0,0,0.55)',
    paddingHorizontal: Spacing.sm,
    paddingVertical: 4,
    borderRadius: Radius.sm,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: 'rgba(255,255,255,0.2)',
  },
  hubEventBadgeText: {
    color: Colors.text,
    fontSize: 11,
    fontWeight: '800',
    letterSpacing: 0.4,
  },
  hubEventBottom: {
    position: 'absolute',
    left: Spacing.md,
    right: Spacing.md,
    bottom: Spacing.md,
    flexDirection: 'row',
    alignItems: 'flex-end',
    gap: Spacing.sm,
  },
  hubEventTitle: {
    color: Colors.text,
    fontSize: 14,
    fontWeight: '700',
  },
  hubEventLoc: {
    fontSize: 11,
    flex: 1,
  },
  hubEventMetaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.sm,
    marginTop: 4,
  },
  hubEventCap: {
    fontSize: 11,
  },
  hubEventStatus: {
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: Radius.pill,
  },
  hubEventStatusPublished: {
    backgroundColor: 'rgba(52,211,153,0.2)',
  },
  hubEventStatusDraft: {
    backgroundColor: 'rgba(40,82,232,0.25)',
  },
  hubEventStatusText: {
    fontSize: 10,
    fontWeight: '700',
  },
  hubEventStatusTextPublished: {
    color: '#34D399',
  },
  hubEventStatusTextDraft: {
    color: Colors.primaryLight,
  },
  hubEventArrow: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: 'rgba(255,255,255,0.12)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  hubStatsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  hubStatCard: {
    backgroundColor: Colors.backgroundElevated,
    borderRadius: Radius.card,
    borderWidth: 0.5,
    borderColor: Colors.borderCard,
    padding: Spacing.lg,
    gap: Spacing.xs,
  },
  hubStatValue: {
    color: Colors.text,
    fontSize: 22,
    fontWeight: '800',
    marginTop: Spacing.xs,
  },
  hubStatLabel: {
    fontSize: 12,
    lineHeight: 16,
  },
});
