import { StyleSheet, Platform, Dimensions } from 'react-native';
import Colors from '../../constants/colors';

const { width } = Dimensions.get('window');

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors.background,
  },
  header: {
    paddingTop: 50,
    paddingHorizontal: 20,
    paddingBottom: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  headerTitle: {
    flex: 1,
    minWidth: 0,
    color: '#fff',
    fontSize: 19,
    fontWeight: '800',
    textAlign: 'center',
    paddingHorizontal: 4,
  },
  backButton: {
    padding: 8,
  },
  backButtonText: {
    color: Colors.primary,
    fontSize: 16,
    fontWeight: '600',
  },
  menuButton: {
    paddingVertical: 8,
    paddingHorizontal: 10,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: 'rgba(77,163,255,0.35)',
    backgroundColor: 'rgba(11,11,14,0.65)',
    minHeight: 44,
    minWidth: 44,
    alignItems: 'center',
    justifyContent: 'center',
  },
  tabsScroll: {
    marginHorizontal: 20,
    marginBottom: 12,
    maxHeight: 52,
  },
  tabsContent: {
    flexDirection: 'row',
    alignItems: 'stretch',
    backgroundColor: 'rgba(255,255,255,0.04)',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.08)',
    paddingVertical: 2,
    paddingHorizontal: 2,
  },
  tabItem: {
    paddingVertical: 12,
    paddingHorizontal: 14,
    alignItems: 'center',
    justifyContent: 'center',
  },
  tabItemActive: {
    backgroundColor: 'rgba(77,163,255,0.18)',
    borderRadius: 8,
  },
  tabText: {
    color: 'rgba(255,255,255,0.85)',
    fontWeight: '600',
    fontSize: 13,
  },
  tabTextActive: {
    color: '#fff',
  },
  content: {
    paddingHorizontal: 20,
  },
  card: {
    backgroundColor: 'rgba(255,255,255,0.04)',
    borderRadius: 12,
    padding: 16,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.08)',
  },
  venueName: {
    color: '#fff',
    fontSize: 22,
    fontWeight: '800',
    marginBottom: 6,
  },
  venueAddress: {
    color: 'rgba(255,255,255,0.7)',
    fontSize: 14,
    marginBottom: 10,
  },
  ratingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 8,
  },
  ratingValue: {
    color: '#fff',
    fontWeight: '700',
  },
  profileButton: {
    marginTop: 8,
    paddingVertical: 12,
    backgroundColor: Colors.primary,
    borderRadius: 10,
    alignItems: 'center',
  },
  profileButtonText: {
    color: Colors.background,
    fontWeight: '700',
  },
  mediaHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  sectionTitle: {
    color: '#fff',
    fontSize: 18,
    fontWeight: '800',
  },
  sectionSubtitle: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '700',
    marginTop: 12,
    marginBottom: 8,
  },
  mediaHint: {
    color: 'rgba(255,255,255,0.6)',
    fontSize: 12,
    marginTop: -4,
    marginBottom: 8,
  },
  mediaActions: {
    flexDirection: 'row',
    gap: 8,
  },
  addFileButton: {
    backgroundColor: Colors.primary,
    paddingVertical: 10,
    paddingHorizontal: 14,
    borderRadius: 8,
  },
  addFileButtonSecondary: {
    backgroundColor: '#444',
  },
  addFileButtonText: {
    color: Colors.background,
    fontWeight: '700',
  },
  photoGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  photoWrapper: {
    position: 'relative',
  },
  photoItem: {
    width: (width - 60) / 2,
    height: 160,
    borderRadius: 10,
    backgroundColor: '#111',
  },
  videoItem: {
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.08)',
    borderRadius: 10,
    overflow: 'hidden',
    backgroundColor: '#111',
    padding: 8,
  },
  videoRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 4,
    paddingTop: 6,
  },
  videoPlaceholder: {
    height: 180,
    borderRadius: 8,
    backgroundColor: '#0d0d11',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.1)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  playIcon: {
    color: Colors.primary,
    fontSize: 32,
    fontWeight: '800',
  },
  videoTitle: {
    color: '#fff',
    padding: 8,
    fontWeight: '600',
  },
  deleteBadge: {
    position: 'absolute',
    top: 6,
    right: 6,
    backgroundColor: 'rgba(0,0,0,0.6)',
    borderRadius: 12,
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  deleteBadgeSmall: {
    backgroundColor: 'rgba(0,0,0,0.6)',
    borderRadius: 12,
    paddingHorizontal: 8,
    paddingVertical: 4,
    marginLeft: 8,
  },
  deleteBadgeText: {
    color: '#fff',
    fontWeight: '800',
  },
  noMedia: {
    color: 'rgba(255,255,255,0.6)',
    marginBottom: 6,
  },
  comingSoon: {
    color: 'rgba(255,255,255,0.6)',
    marginTop: 8,
  },
  ratingCard: {
    backgroundColor: 'rgba(255,255,255,0.02)',
    borderRadius: 10,
    padding: 12,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.08)',
  },
  ratingDetail: {
    color: 'rgba(255,255,255,0.7)',
    marginTop: 6,
  },
  reviewsList: {
    marginTop: 10,
    gap: 10,
  },
  reviewItem: {
    backgroundColor: 'rgba(255,255,255,0.04)',
    borderRadius: 8,
    padding: 10,
  },
  reviewHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 4,
  },
  reviewRating: {
    color: Colors.primary,
    fontWeight: '800',
  },
  reviewMeta: {
    color: 'rgba(255,255,255,0.6)',
    fontSize: 12,
  },
  reviewComment: {
    color: '#fff',
  },
  loaderScreen: {
    flex: 1,
    backgroundColor: Colors.background,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 20,
  },
  loadingText: {
    color: '#fff',
    marginTop: 12,
    textAlign: 'center',
  },
  // Bookings
  bookingsList: { gap: 12 },
  bookingCard: {
    backgroundColor: 'rgba(255,255,255,0.04)',
    borderRadius: 12,
    padding: 14,
    borderWidth: 1,
    borderColor: 'rgba(77,163,255,0.25)',
  },
  bookingHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: 10 },
  bookingTitle: { color: '#fff', fontSize: 16, fontWeight: '800', flex: 1, minWidth: 0, paddingRight: 8 },
  bookingStatus: { paddingHorizontal: 8, paddingVertical: 4, borderRadius: 8 },
  bookingStatusText: { fontSize: 12, fontWeight: '700' },
  bookingInfo: { marginBottom: 6 },
  bookingInfoLabel: { color: 'rgba(255,255,255,0.6)', fontSize: 12, marginBottom: 2 },
  bookingInfoValue: { color: '#fff', fontSize: 14, fontWeight: '600' },
  chatButton: {
    paddingVertical: 10,
    paddingHorizontal: 14,
    borderRadius: 10,
    backgroundColor: Colors.primary,
    alignItems: 'center',
  },
  bookingActionsRow: { flexDirection: 'row', gap: 10, marginTop: 12, alignItems: 'stretch' },
  bookingActionPrimary: { justifyContent: 'center' },
  bookingActionDestructive: {
    paddingVertical: 10,
    paddingHorizontal: 14,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'transparent',
    borderWidth: 2,
    borderColor: 'rgba(255,82,82,0.9)',
  },
  bookingActionDestructiveText: { color: '#FF8A80', fontWeight: '800', fontSize: 14 },
  chatButtonText: { color: Colors.background, fontWeight: '800', fontSize: 14 },
  // Chat modal
  chatModalContainer: { flex: 1, backgroundColor: 'rgba(0,0,0,0.8)' },
  chatModalContent: {
    flex: 1,
    backgroundColor: Colors.background,
    marginTop: Platform.OS === 'ios' ? 50 : 0,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    maxHeight: '100%',
  },
  chatHeaderContainer: { zIndex: 10 },
  chatHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: 16,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255,255,255,0.1)',
    backgroundColor: 'rgba(26,26,31,0.95)',
  },
  chatCloseButton: { width: 40, height: 40, alignItems: 'center', justifyContent: 'center' },
  chatCloseButtonText: { color: '#fff', fontSize: 24, fontWeight: '300' },
  chatHeaderTitle: { color: '#fff', fontSize: 18, fontWeight: '700' },
  contractCard: {
    marginHorizontal: 16,
    marginTop: 10,
    marginBottom: 6,
    padding: 12,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: 'rgba(77,163,255,0.22)',
    backgroundColor: 'rgba(77,163,255,0.06)',
  },
  contractTopRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 10 },
  contractTitle: { color: '#fff', fontSize: 14, fontWeight: '800' },
  contractStatus: { color: Colors.primary, fontSize: 12, fontWeight: '800' },
  contractMeta: { marginTop: 6, color: '#fff', fontSize: 12, fontWeight: '700' },
  contractLine: { marginTop: 6, color: 'rgba(255,255,255,0.7)', fontSize: 12 },
  contractLineStrong: { color: '#fff', fontWeight: '900' },
  contractSmall: { marginTop: 4, color: 'rgba(255,255,255,0.6)', fontSize: 11 },
  contractActionsRow: { marginTop: 10, flexDirection: 'row', alignItems: 'center', justifyContent: 'flex-end', gap: 10 },
  contractPdfPreviewBtn: { alignSelf: 'stretch', marginTop: 8, marginBottom: 2 },
  contractHint: { color: 'rgba(255,255,255,0.6)', fontSize: 12, fontWeight: '700' },
  contractAckRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginTop: 10,
    marginBottom: 4,
    paddingRight: 4,
  },
  contractAckCheckbox: {
    width: 22,
    height: 22,
    borderRadius: 6,
    borderWidth: 2,
    borderColor: 'rgba(77,163,255,0.55)',
    marginRight: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  contractAckCheckboxChecked: {
    backgroundColor: Colors.primary,
    borderColor: Colors.primary,
  },
  contractAckCheckmark: {
    color: Colors.background,
    fontSize: 14,
    fontWeight: '800',
  },
  contractAckText: {
    flex: 1,
    color: 'rgba(255,255,255,0.88)',
    fontSize: 11,
    lineHeight: 16,
    fontWeight: '600',
  },
  contractButton: {
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderRadius: 12,
    minHeight: 40,
    alignItems: 'center',
    justifyContent: 'center',
  },
  contractButtonPrimary: { backgroundColor: Colors.primary },
  contractButtonSecondary: {
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.22)',
    backgroundColor: 'rgba(0,0,0,0.18)',
  },
  contractButtonText: { color: '#fff', fontSize: 12, fontWeight: '800' },
  contractButtonTextDark: { color: Colors.background, fontSize: 12, fontWeight: '900' },
  chatLoadingContainer: { padding: 40, alignItems: 'center' },
  chatMessagesContainer: { padding: 16, paddingBottom: 20 },
  chatEmptyState: { padding: 30, alignItems: 'center' },
  chatEmptyStateText: { color: 'rgba(255,255,255,0.6)', fontSize: 14,
    textAlign: 'center' },
  chatMessage: { marginBottom: 10 },
  chatMessageOwn: { alignItems: 'flex-end' },
  chatMessageOther: { alignItems: 'flex-start' },
  chatMessageBubble: {
    maxWidth: '80%',
    padding: 12,
    borderRadius: 16,
    borderWidth: 1,
  },
  chatMessageBubbleOwn: {
    backgroundColor: 'rgba(77,163,255,0.25)',
    borderColor: 'rgba(77,163,255,0.4)',
  },
  chatMessageBubbleOther: {
    backgroundColor: 'rgba(255,255,255,0.08)',
    borderColor: 'rgba(255,255,255,0.12)',
  },
  chatMessageBubbleDeleted: { opacity: 0.6 },
  chatMessageText: { fontSize: 15 },
  chatMessageTextOwn: { color: '#fff' },
  chatMessageTextOther: { color: '#fff' },
  chatMessageTextDeleted: { color: 'rgba(255,255,255,0.5)', fontStyle: 'italic' },
  chatMessageTime: { fontSize: 11, marginTop: 4 },
  chatMessageTimeOwn: { color: 'rgba(255,255,255,0.6)' },
  chatMessageTimeOther: { color: 'rgba(255,255,255,0.5)' },
  chatInputContainer: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    padding: 12,
    borderTopWidth: 1,
    borderTopColor: 'rgba(255,255,255,0.1)',
    backgroundColor: 'rgba(26,26,31,0.95)',
    gap: 10,
  },
  chatInput: {
    flex: 1,
    backgroundColor: 'rgba(255,255,255,0.08)',
    borderRadius: 10,
    paddingHorizontal: 14,
    paddingVertical: 10,
    color: '#fff',
    fontSize: 15,
    maxHeight: 100,
  },
  chatSendButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: Colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  chatSendButtonDisabled: { opacity: 0.5 },
  chatSendButtonText: { color: Colors.background, fontSize: 18, fontWeight: '800' },
  contractModalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.65)',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 18,
  },
  contractModalCard: {
    width: '100%',
    maxWidth: 520,
    borderRadius: 16,
    padding: 14,
    borderWidth: 1,
    borderColor: 'rgba(77,163,255,0.25)',
    backgroundColor: Colors.background,
  },
  contractModalTitle: { color: '#fff', fontSize: 16, fontWeight: '900', marginBottom: 10 },
  contractModalLabel: { color: 'rgba(255,255,255,0.7)', fontSize: 12, fontWeight: '700', marginTop: 10, marginBottom: 6 },
  contractModalInput: {
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.15)',
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 10,
    color: '#fff',
    backgroundColor: 'rgba(255,255,255,0.04)',
    fontSize: 13,
  },
  contractModalDropdown: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  contractModalInputText: { color: '#fff', fontSize: 13, flex: 1 },
  contractModalChevron: { color: 'rgba(255,255,255,0.5)', fontSize: 10, marginLeft: 8 },
  contractModalActions: { flexDirection: 'row', gap: 10, marginTop: 16, justifyContent: 'flex-end' },
  paymentTermsOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.65)',
    justifyContent: 'center',
    padding: 18,
  },
  paymentTermsModalContent: {
    backgroundColor: Colors.background,
    borderRadius: 16,
    padding: 14,
    borderWidth: 1,
    borderColor: 'rgba(77,163,255,0.3)',
    maxWidth: 400,
    width: '100%',
    alignSelf: 'center',
  },
  paymentTermOption: {
    padding: 14,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255,255,255,0.08)',
  },
  paymentTermOptionText: { color: '#fff', fontSize: 15, fontWeight: '600' },
  paymentTermsOption: {
    padding: 14,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255,255,255,0.08)',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  paymentTermsOptionSelected: { backgroundColor: 'rgba(77,163,255,0.12)' },
  paymentTermsOptionText: { color: '#fff', fontSize: 15, fontWeight: '600', flex: 1 },
  paymentTermsOptionTextSelected: { color: Colors.primary },
  paymentTermsCheck: { color: Colors.primary, fontSize: 16, fontWeight: '800' },
  paymentTermsClose: { marginTop: 12, padding: 12, alignItems: 'center' },
});
